version:     0.0.6
safe:        false
auto:        false
server:      false

baseurl:     http://sunnyjs.org/
source:      .
destination: ../docs_html
plugins:     ./_plugins
exclude:     ["css"]

future:      true
lsi:         false
pygments:    true
markdown:    maruku
permalink:   date
